### ISSUE TITLE
`sphinx.ext.autodoc` link is broken

### ISSUE THREAD

**Issue by choldgraf** [sphinx-themes/sphinx-themes.org#101]
Example here: https://sphinx-themes.org/sample-sites/default-alabaster/kitchen-sink/api/#api-documentation

I think this is because the docs use `` :any:`sphinx.ext.autodoc` `` but it is not a valid ref.

**Comment by pradyunsg** [comment]
A PR would be welcome for this. :)

**Comment by choldgraf** [comment]
I just wasn't sure what the intended behavior was, autodoc is quite mysterious to me so I didn't know if there was some feature you were trying to use that I didn't undersr

**Comment by pradyunsg** [comment]
I think we need intersphinx to include Sphinx itself, to add a cross link to that.

**Comment by mgeier** [comment]
This should be fixed by #147.
