### ISSUE TITLE
PyData theme demo broken (build failed)

### ISSUE THREAD

**Issue by pierre-haessig** [sphinx-themes/sphinx-themes.org#105]
I believe that the PyData theme demo (https://sphinx-themes.org/sample-sites/pydata-sphinx-theme/) is broken, with the build error message ending with:

```
Theme error:
An error happened in rendering the page index.
Reason: KeyError('https://www.sphinx-doc.org')
```

**Comment by pradyunsg** [comment]
Please report this to pydata-sphinx-theme, as this is a valid Sphinx documentation set that is supposed to work, and is broken with their newest release.

**Comment by pierre-haessig** [comment]
OK, I've commented https://github.com/pydata/pydata-sphinx-theme/issues/913 to see if it's related.
