### ISSUE TITLE
New theme: <no PyPI name, from manticore-projects.com>

### ISSUE THREAD

**Issue by manticore-projects** [sphinx-themes/sphinx-themes.org#106]
Greetings!

I have been searching for a very long time for suitable theme, but did not really find anything pleasant:
1) most themes do not cater very wide screens well
2) color and styling is debatable
3) no landing page support

The nicest theme matching my taste is [REVITRON](https://github.com/revitron/revitron-sphinx-theme), however it has technical shortcomings.

Long story short, I ended up with developing my own theme, forking from https://github.com/readthedocs/sphinx_rtd_theme

It scales very well on wide screens and mobile phones, it has a landing page, it supports 2 accent colors and it does not need NodeJS or NPM.

You can see it in action here: http://manticore-projects.com

![image](https://user-images.githubusercontent.com/18080123/188505356-4a9aabb6-349f-43cf-8a6c-43e81f3e8192.png)

At the moment, the theme is merely a Blob, which one would drop into the ``./_themes`` folder. No PIP/Python involved or need.

Would you be interested in listing it? And what would you need from my end to make that happen please?

**Comment by pradyunsg** [comment]
Thanks for filing this issue! We'd be happy to list it! :)

See https://github.com/sphinx-themes/sphinx-themes.org/blob/master/CONTRIBUTING.md for the details on how to contribute new themes.

One notable requirement is that the theme needs to be pip installable and, typically, this also makes them usable by setting "just" the `html_theme` variable. See http://www.sphinx-doc.org/en/stable/theming.html#distribute-your-theme-as-a-python-package for the details on that.

**Comment by manticore-projects** [comment]
thank you for the heads up. I will work through accordingly.

**Comment by pradyunsg** [comment]
Awesome, when you have a PyPI name, please feel welcome to update this issue's title to reflect that. :)

**Comment by manticore-projects** [comment]
> See http://www.sphinx-doc.org/en/stable/theming.html#distribute-your-theme-as-a-python-package for the details on that.

Apologies for asking, but this site does not seem to exist.

**Comment by pradyunsg** [comment]
Hey @manticore-projects! Any updates on this?

**Comment by pradyunsg** [comment]
Closing this out, since there don't seem to be any updates on this.
