### ISSUE TITLE
Use stable Sphinx for building the "default" images

### ISSUE THREAD

**Issue by humitos** [sphinx-themes/sphinx-themes.org#114]
Hi! I'm opening this issue because of this comment from @pradyunsg 

> @humitos Those are themes being broken with Sphinx 6 (part of the goal with this site was to have it automatically test Sphinx pre-releases across themes). It's mildly concerning that alabaster is failing with Sphinx 6. :)

_(from https://github.com/sphinx-themes/sphinx-themes.org/issues/113#issuecomment-1285327572)_

I think it's really good to build all the themes with the latest beta release from Sphinx because it helps developers to know if their theme is going to work once that version of Sphinx becomes stable. However, from a Sphinx's user perspective, it's not good to be pointed to this site to decide which theme to use and realize that some of them are broken.

Besides, from a marketing perspective, it's not good for the Sphinx ecosystem in general, to refer to this site as the canonical place to find really good themes and decide which one to use, but find there are some that are broken.

That said, I think it would be awesome if we could have two different versions of this site:

- public facing using the latest _stable_ release for Sphinx
- developer facing using the latest _beta_ release for Sphinx

---

I went ahead and tried this using Read the Docs:

* Latest stable Sphinx:
  * Public URL: https://sphinx-themes.readthedocs.io/en/latest/
  * GitHub repository: https://github.com/humitos/sphinx-themes.org/tree/readthedocs
* Latest _beta_ Sphinx:
  * Public URL: https://sphinx-themes.readthedocs.io/en/pre-sphinx/
  * GitHub repository: https://github.com/humitos/sphinx-themes.org/tree/pre-sphinx
* Project: https://readthedocs.org/projects/sphinx-themes/

I'm happy to rebase the commits and create a PR if you consider this work useful. If you like this work, but want to keep using GH pages to host the both versions, we can figure it out how to do it there as well. Let me know.

**Comment by pradyunsg** [comment]
I'm fine with making a split on this site -- I'd still prefer to have a single landing page though for this; and have different Sphinx versions be presented under a dropdown or something. :)

**Comment by pradyunsg** [comment]
> Besides, from a marketing perspective, it's not good for the Sphinx ecosystem in general, to refer to this site as the canonical place to find really good themes and decide which one to use, but find there are some that are broken.

Agreed. With #115, I've switched to using the stable Sphinx release for themes.

> That said, I think it would be awesome if we could have two different versions of this site:
> 
>     * public facing using the latest _stable_ release for Sphinx
>     * developer facing using the latest _beta_ release for Sphinx

Let's track this separately. I've opened #116 for this.

**Comment by humitos** [comment]
> I'd still prefer to have a single landing page though for this; and have different Sphinx versions be presented under a dropdown or something. :)

I'd love to see this 😍 . I like the idea 💯
