### ISSUE TITLE
Add sphinx-typo3-theme

### ISSUE THREAD

**Issue by ghaefele** [sphinx-themes/sphinx-themes.org#12]
Please add the new Sphinx Typo3 Theme (successor of t3SphinxThemeRtd).

PyPI: https://pypi.org/project/sphinx-typo3-theme/
Repository: https://github.com/TYPO3-Documentation/sphinx_typo3_theme

**Comment by shirou** [comment]
Thank you for inform. It has been added https://sphinx-themes.org/html/sphinx-typo3-theme/sphinx_typo3_theme/index.html
