### ISSUE TITLE
Build Failed!

### ISSUE THREAD

**Issue by mgeier** [sphinx-themes/sphinx-themes.org#122]
I don't know if this has been reported yet, but most theme examples are currently broken and show an error message.

Maybe this has to do with the release of Sphinx 6?

**Comment by pradyunsg** [comment]
It is, we're missing a `%s` in the extlinks configuration. Sphinx should really have better error messages around this stuff. 🤦🏽 

x-ref #112

**Comment by pradyunsg** [comment]
Thanks for reporting this @mgeier! ^.^
