### ISSUE TITLE
the pydata-sphinx-theme is crashing

### ISSUE THREAD

**Issue by 12rambau** [sphinx-themes/sphinx-themes.org#128]
With sphinx 6 we had lots of issues with the logo management, problems that will be solved in v0.13. pinning @choldgraf to add an example to my point: we should make patch releases instead of release candidates as many are relying on the released version

**Comment by choldgraf** [comment]
Go for it - I am happy for somebody to make a release, I just haven't had time because I've been sick.

**Comment by 12rambau** [comment]
Just closing this one as the latest release have solved it
