### ISSUE TITLE
Numerous builds failing with Sphinx 7.0.0

### ISSUE THREAD

**Issue by vsajip** [sphinx-themes/sphinx-themes.org#133]
Numerous theme builds are failing with Sphinx 7.0.0 - I've updated my theme to work with it and released the update to PyPI. How often are theme builds triggered to incorporate theme changes/releases?

**Comment by shirou** [comment]
Thanks for letting us know.
CI is done automatically [every Monday](https://github.com/sphinx-themes/sphinx-themes.org/blob/master/.github/workflows/ci.yaml#L8).

**Comment by vsajip** [comment]
Thanks for the info!
