### ISSUE TITLE
Add Sphinx NervProject Theme

### ISSUE THREAD

**Issue by kujiu** [sphinx-themes/sphinx-themes.org#15]
Hello,
I've just finished my website and I created a theme based on sphinx_press_theme (to use with ablog). I'll be pleased if someone reuse it. So can you add it please ?

https://pypi.org/project/sphinx-nervproject-theme
https://procrastinator.nerv-project.eu/nerv-project/communication/sphinx_nervproject_theme

Thanks a lot !

**Comment by shirou** [comment]
Thank you for your request! I have added at [here](https://sphinx-themes.org/html/sphinx-nervproject-theme/nervproject/index.html)!
