### ISSUE TITLE
Build failures for several themes

### ISSUE THREAD

**Issue by adamjstewart** [sphinx-themes/sphinx-themes.org#152]
The following themes on https://sphinx-themes.org/ display build errors:

* Basicstrap
* Bernard
* Hachibee
* Karma
* Kotti
* Murray
* Redactor
* Sizzle
* Stanford
* Topos
* Yummy

Not sure if something changed that broke them.

**Comment by pradyunsg** [comment]
Spot checking a couple of them, they're failing with:

```
sphinx.errors.ThemeError: An error happened in rendering the page index.
Reason: UndefinedError("'style' is undefined")
```

They look like they're incompatible with Sphinx 7 and don't declare that: https://github.com/sphinx-doc/sphinx/pull/11381

**Comment by pradyunsg** [comment]
Consolidating into #156
