### ISSUE TITLE
Please add Sizzle theme

### ISSUE THREAD

**Issue by vsajip** [sphinx-themes/sphinx-themes.org#16]
Please add this theme:

https://github.com/vsajip/sphinx_sizzle_theme

Available from PyPI:

https://pypi.org/project/sphinx-sizzle-theme/

**Comment by shirou** [comment]
Thank you for reporting, I have added at [here](https://sphinx-themes.org/html/sphinx_sizzle_theme/sizzle/index.html)!

**Comment by vsajip** [comment]
Thanks very much!
