### ISSUE TITLE
Thoughts on a revamp?

### ISSUE THREAD

**Issue by pradyunsg** [sphinx-themes/sphinx-themes.org#17]
Following https://github.com/sphinx-themes/sphinx-themes.org/issues/3#issuecomment-660598014, I spent a few cycles iterating on this and came up with https://github.com/pradyunsg/sphinx-themes. I added a few themes to demonstrate the approach and a very basic/minimal index page for this, which [is online now](https://pradyunsg.me/sphinx-themes/).

I started from-scratch and came away with quite a different approach for doing things. This resulted in:

- Generating demos, and screenshots (w/ selenium) in a GitHub Action job.
- Keep all theme-related information in a JSON file.
- No requirement on docker -- plain Python scripts w/ [nox](https://nox.readthedocs.io/).
- No generated HTML/CSS/images are checked into the master branch.
- Preview images contain multiple viewport sizes! :tada:

Notably, the main changes due to all of this are:

- Significantly lower barrier for adding new themes! :tada:
- Themes have to be installable from PyPI, usable against the current Sphinx version
  - This is a reasonable assumption, and helps ensure that people can actually use the themes. :)
- No conf.py is included/provided
  - The theme should have documentation about this, so the gallery doesn't need to cover this.
  - It should be easy-enough to add this if we really want to (I don't)
- 2 column vs 3 column layout
  - I wanted this to include additional viewport sizes, so, yea, I think this design change is worthwhile. :)

---

This was mostly an over-the-boring-day thing, and there's definitely scope for improvement in the automation (eg: separating render-with-themes vs generate-screenshots). If there's interest in bringing in most (all?) of that codebase into this one, I'd like to hear about it! ^>^

**Comment by shirou** [comment]
Awesome! It looks super nice! replace Docker to nox, 2 column layout, multiple viewport, and many of sample rst directives!

However, why I include `conf.py` is, many of themes especially old Sphinx version, has uses different way to install from current Sphinx version. so I had to edit conf.py to install and use it. So I want to include a final version of conf.py.

Please see [log.csv](https://github.com/sphinx-themes/sphinx-themes.org/blob/master/log.csv). I can not remember exact meaning but for example, `sphinx-better-theme,completed,import`, the last `import` means I should change import path. If you want to ignore those themes, it's ok.


Anyway, I love your work and I want to replace my work with yours.

**Comment by pradyunsg** [comment]
> If you want to ignore those themes, it's ok.

We can definitely accomodate for them -- see edx-sphinx-theme in [themes.json](https://github.com/pradyunsg/sphinx-themes/blob/master/themes.json) file.

We can add the themes that need custom configuration as well. I've described this detail of the themes.json entries in more detail in the CONTRIBUTING page: https://github.com/pradyunsg/sphinx-themes/blob/master/.github/CONTRIBUTING.md#complex-theme-configuration.

> So I want to include a final version of conf.py.

Fair enough. I guess I should just copy the file over, and add a link somewhere in the UI. :)

> Anyway, I love your work

Thank you! ^>^

> I want to replace my work with yours.

Hmm... How should we go about doing this? Making a PR would be tricky, since the history is completely different. If we're OK with losing the commit history, it should be easy enough to set everything up by just force-pushing that repo over this one.

**Comment by yuvipanda** [comment]
> Making a PR would be tricky, since the history is completely different. If we're OK with losing the commit history, it should be easy enough to set everything up by just force-pushing that repo over this one.

You can use `--allow-unrelated-histories` with git merge to do this while preserving history.

1. Take current repo
2. Make a commit deleting everything
3. Add new repo as remote
4. Merge new repo's branch into current branch, passing `--allow-unrelated-histories` to `git merge`
5. Tada! You have preserved history & credit without having to do super weird git stuff.

Hope that helps :)

**Comment by pradyunsg** [comment]
> --allow-unrelated-histories  

TIL!

Looks like I can file a PR doing this! Hurray! I'll cut today's pip release and then come back to this. :)

**Comment by pradyunsg** [comment]
Thanks @yuvipanda for that! I've gone ahead and filed #19 which synchronizes pradyunsg.me/sphinx-themes with this project. I'd like to add the delta of themes in a follow up PR, because I don't want to keep updating two branches as I do so. :)

**Comment by shirou** [comment]
I read the CONTRIBUTING.md and it is extendable and flexible. Great! many old themes uses `html_theme_path` something like `html_theme_path = [kotti_docs_theme.get_theme_dir()]` but this type of theme is already coverted. so no concern about it.

But, ah, sorry, I have a new concern. From my understanding, this renders all themes whenever deployed. from [github action logs](https://github.com/pradyunsg/sphinx-themes/actions) it takes 5min for 23 themes. So if build for current 115 themes, it might takes 25-30mins. Is it true?
GitHub Free plan includes 2,000 mins/month. so 25-30 mins is not so problem. but I want to clarify my understanding.

**Comment by pradyunsg** [comment]
> So if build for current 115 themes, it might takes 25-30mins. Is it true?

Yes, I think so. I do have some ideas for how to optimize this (parallelize the screenshotting logic, cache builds when sphinx-version+theme-version doesn't change etc).

I don't think there's any good way to justify the effort to do these tho, not until this starts becoming a workflow issue.

> GitHub Free plan includes 2,000 mins/month. so 25-30 mins is not so problem. but I want to clarify my understanding.

Note that this limit is for private repositories. Public repositories do not count toward this limit (I know, because I can see this in the billing area).

They're still required to comply by the overall general use policies, which we clearly do IMO. :)

**Comment by pradyunsg** [comment]
Nudge.

**Comment by pradyunsg** [comment]
>  From my understanding, this renders all themes whenever deployed. from [github action logs](https://github.com/pradyunsg/sphinx-themes/actions) it takes 5min for 23 themes.

With #22 and #23, this is down to 3.5 minutes. :)
