### ISSUE TITLE
How to add a new theme?

### ISSUE THREAD

**Issue by schettino72** [sphinx-themes/sphinx-themes.org#2]
The instructions are not very clear. Step 3 says

```
PKG_NAME= <pass pkg-name> THEME= <pass theme name> make build run
```

Where?

I would like to add https://github.com/schettino72/sphinx_press_theme

PKG_NAME=sphinx_press_theme
THEME=press

**Comment by shirou** [comment]
Currently, only I can add a theme because it is using github  or you can create a PR.

But, I already add your beautiful theme at [here](https://sphinx-themes.org/html/sphinx-press-theme/press/index.html) ! Sorry there are no search function but you can search by your self in this page.

**Comment by schettino72** [comment]
Oh. you are fast. 

I was planning to create a PR but did not understand how to do it. 

Anyway you already did it thanks :smile:
