### ISSUE TITLE
New Theme: sphinx_documatt_theme

### ISSUE THREAD

**Issue by mattdocumatt** [sphinx-themes/sphinx-themes.org#20]
Hello, is it possible to add my "Documatt Theme"? It was originally for just my blog, but I open-sourced it recently.

- package name is `sphinx-documatt-theme`, but `html_theme` is `sphinx_documatt_theme`.
- PyPI: https://pypi.org/project/sphinx-documatt-theme/
- real demo: https://blog.documatt.com/

Thanks!

**Comment by pradyunsg** [comment]
Hi @mattdocumatt! Thanks for filing this issue! ^>^

Please look at [Adding a new theme](https://github.com/sphinx-themes/sphinx-themes.org/blob/master/CONTRIBUTING.md#adding-a-new-theme) for details for how to file a PR adding a new theme to this website. :)

**Comment by mattdocumatt** [comment]
Oh :facepalm: closing this issue, and proposing https://github.com/sphinx-themes/sphinx-themes.org/pull/28
