### ISSUE TITLE
Could not open the "How to create" from sphinx-themes.org 

### ISSUE THREAD

**Issue by Mariatta** [sphinx-themes/sphinx-themes.org#21]
I went to https://sphinx-themes.org/ and from the top left menu, then I chose the "How to create" link. It brought me to https://www.sphinx-doc.org/en/master/theming.html#creating-themes which is 404.

It would be great if the url can be fixed somehow. Thanks.

**Comment by shirou** [comment]
Oh, so it has moved. Since we are recreating by #19,  I will fix after recreating finished. Thank you for the information!

**Comment by pradyunsg** [comment]
Closing since this link no longer exists on the site! :)
