### ISSUE TITLE
[idea] Sub-divide themes

### ISSUE THREAD

**Issue by schettino72** [sphinx-themes/sphinx-themes.org#3]
IMO it would be better if the front-page showed **less** themes.
There is a lot of themes there are just a small variation and/or branding of another theme.

What about front-page show only the main theme and its variations being displayed on another page?
This way it would make it easier to explore available theme families,
and after selecting a base theme a user could see its variations.

ps. You know i am an author of a theme, so I am biased here...

**Comment by shirou** [comment]
Agree.  I also want to implement separeting to pages, search, sort by download, and so on. But I have no time...

**Comment by pradyunsg** [comment]
@shirou Would you be willing to accept contributions on this project?

**Comment by shirou** [comment]
Contributions are allways welcome!

**Comment by pradyunsg** [comment]
> IMO it would be better if the front-page showed less themes.

Indeed!

> What about front-page show only the main theme and its variations being displayed on another page?

With changes made in #17, we're limiting each theme to only showing up once (by requiring every theme to be on PyPI, and only allowing 1 entry per PyPI package). So, this is no longer a concern.

> This way it would make it easier to explore available theme families, and after selecting a base theme a user could see its variations.

I'd say #24 should enable users to know about potential "theme families" (we add a tag for each family).

---

I'll close this in favor of that issue. Let me know if you have something else in mind that isn't covered by that issue. :)
