### ISSUE TITLE
New Theme: Sphinx Typlog Theme

### ISSUE THREAD

**Issue by frostming** [sphinx-themes/sphinx-themes.org#4]
I found a new elegant theme: Sphinx Typlog Theme

PyPI: https://pypi.org/project/sphinx-typlog-theme/
Sample: https://sphinx-typlog-theme.readthedocs.io/

**Comment by pradyunsg** [comment]
Thanks for filing this issue! ^.^

In case you're interested in filing a PR, I've added instructions for [Adding a new theme](https://github.com/sphinx-themes/sphinx-themes.org/blob/master/CONTRIBUTING.md#adding-a-new-theme) to v2 of this website. :)

**Comment by pradyunsg** [comment]
Fixed through #27.
