### ISSUE TITLE
Add sphinx-material theme

### ISSUE THREAD

**Issue by lordmauve** [sphinx-themes/sphinx-themes.org#5]
Another material theme: https://github.com/bashtage/sphinx-material

**Comment by shirou** [comment]
Please create 
- add_html_theme
- get_path

then, sphinx can get your theme automatically.

see http://www.sphinx-doc.org/en/master/theming.html for doc and 
https://github.com/typlog/sphinx-typlog-theme is a sample.

**Comment by mgeier** [comment]
I have done this in https://github.com/bashtage/sphinx-material/pull/43.

**Comment by shirou** [comment]
Thank you so much! I have added at [here](https://sphinx-themes.org/html/sphinx-material/sphinx_material/index.html)!

**Comment by pradyunsg** [comment]
This issue can be closed.

**Comment by shirou** [comment]
ok, thank you!
