### ISSUE TITLE
Permitting multiple themes from a single PyPI package 

### ISSUE THREAD

**Issue by shirou** [sphinx-themes/sphinx-themes.org#63]
One Sphinx theme packages can have multiple themes. However, v2 can not handle such a package. A package can have a only one theme.

Example

- [pylons-sphinx-themes](https://pypi.org/project/pylons-sphinx-themes/) has pylons, pyramid, and pylonsfw themes.

**Comment by pradyunsg** [comment]
From the PR that triggered this:

> The one-theme-per-package is also a specific design choice (there's a bunch of hoops to jump to allow for that which feels unnecessary) and I'd rather we nudge downstream authors to, well, have one theme per package.
>
>> but why not?
>
> no good-looking reusable theme does this. We can revisit and explore adding this complexity if such a theme is ever created.
>
>> multiple themes in one package is a Sphinx's design choice.
>
> Well, yes. But until some "relevant" theme uses it, this is unnecessary complexity.

**Comment by pradyunsg** [comment]
To be clear, I don't think this is a blocker to switching from v1 to v2, since no theme authors have brought this up themselves yet; and if they do, I'm very happy to look into this.

Until then, this is feels very YAGNI.

**Comment by shirou** [comment]
Agree. I will change DNS settings in this weekend. Thank you for your great contribution!

**Comment by pradyunsg** [comment]
> Until then, this is feels very YAGNI.

I'm gonna call it this and close this for now. If any theme author sees this and wants it, please file a new issue; and I'll be happy to add this in. :)
