### ISSUE TITLE
Provide a link to the Sphinx documentation about using a theme

### ISSUE THREAD

**Issue by choldgraf** [sphinx-themes/sphinx-themes.org#66]
I suspect that many people landing on this website will be new to the Sphinx ecosystem, and will be trying to find a theme that works with their documentation. For many, it may be unclear how to set a new theme in the Sphinx configuration and this is the first site they land on. It would be helpful if there were a link somewhere on the website that said something like "For information about how to configure Sphinx to use a theme, see [the Sphinx theming documentation](https://www.sphinx-doc.org/en/master/usage/theming.html)"

**Comment by pradyunsg** [comment]
This is now covered by "quickstart" in the theme sample sites, which clearly lays out the steps for how to use the theme.

**Comment by pradyunsg** [comment]
https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/quickstart/

Should've included a link!
