### ISSUE TITLE
Website is 404

### ISSUE THREAD

**Issue by mgeier** [sphinx-themes/sphinx-themes.org#67]
When visiting https://sphinx-themes.org/, I get a 404 page from Github pages.

**Comment by pradyunsg** [comment]
Hmm... I thought this'd get fixed by https://github.com/sphinx-themes/sphinx-themes.org/pull/65#issuecomment-787084440.

**Comment by pradyunsg** [comment]
Okay, so https://sphinx-themes.github.io/sphinx-themes.org/ is still working.

**Comment by shirou** [comment]
I did nothing but `custom domain` setting was blanked. it seems fixed now.

**Comment by shirou** [comment]
I'm quite surprised the settings was erased. GitHub did something?

**Comment by pradyunsg** [comment]
Ah, the CNAME file. It wasn’t being generated and then it was being generated in the wrong directory. Let’s see if my latest push fixed it. :)

**Comment by pradyunsg** [comment]
Fixed by https://github.com/sphinx-themes/sphinx-themes.org/commit/2c45a9b74baa4aeecfa863386677e7b1009f2317! :)
