### ISSUE TITLE
Demo does not test/showcase ``.. content::`` directive

### ISSUE THREAD

**Issue by latosha-maltba** [sphinx-themes/sphinx-themes.org#68]
The demo document (more precisely src/demo.rst) does not showcase the `..contents::` directive.
The `..content::` directive is present but assigned the `:local:` parameter so that only headings in that section are reference.
However that section does not provide any further headings and as a result the `.. contents::` directive does not provide any output.

Possible solutions:
a) Remove the `:local:` parameter, that way all headings of the entire document are collected, shown and referenced.
b) Add some (dummy) subheadings in the section of the `..contents::` directive, so these headings are collected and shown. In this case it might also be worth adding sub-sub-headings, so that the layout of nested sections in `..contents::` is observed.

Sidenote: It might or might not be worth adding `:backlinks: none` parameter to `..contents::` depending on what one wants to demonstrate.

If you like, I'll provide a pull request, though you must point out which solution you'll like to see.

**Comment by latosha-maltba** [comment]
Since I didn't get an answer, I did something(tm).

**Comment by pradyunsg** [comment]
Closing since #84 is merged.
