### ISSUE TITLE
Removed unmaintained themes from "featured" list?

### ISSUE THREAD

**Issue by mgeier** [sphinx-themes/sphinx-themes.org#76]
Nothing against those themes, but I think they shouldn't be "featured".

* Alabaster
  * last release in Oct 2018: https://pypi.org/project/alabaster/#history
  * no more activity on Github (even though there are many issues and PRs): https://github.com/bitprophet/alabaster

* Redactor
  * only one release ever, in July 2017: https://pypi.org/project/sphinx-redactor-theme/#history
  * repo doesn't seem to exist anymore: https://github.com/testthedocs/sphinx_redactor_theme

Celery, Insegel and Press don't seem to be very active either, but probably they are just very stable and bug-free?

The situation with Alabster is strange because it's Sphinx's default theme, but that doesn't change that it's not maintained anymore.

**Comment by pradyunsg** [comment]
I'll keep Alabaster, given that it's the default, but given that Redactor is unmaintained, removing it makes a lot of sense.

**Comment by pradyunsg** [comment]
Closed by 7f291b6d52f275746aa13849a003dd8247c20508.
