### ISSUE TITLE
The Stanford demo is failing

### ISSUE THREAD

**Issue by DiddiLeija** [sphinx-themes/sphinx-themes.org#94]
Seems like https://sphinx-themes.org/sample-sites/stanford-theme/ is failing. The output says:

```
Could not install: stanford-theme
```

Not sure why, but I suppose it is because of the classifiers (see [here](https://pypi.org/project/sphinx-theme/)), or maybe the build from source failed?

**Comment by shirou** [comment]
Thank you for your report. I also confirmed it failed. Perhaps this theme can not follow the sphinx version up. Too sad, but we will delete this theme from targets.

**Comment by shirou** [comment]
My understanding was wrong. This fail is because from miss-configuration. fixes in #95.

**Comment by DiddiLeija** [comment]
Thanks @shirou!

**Comment by DiddiLeija** [comment]
The only thing is that now the link for Stanford is https://sphinx-themes.org/sample-sites/sphinx-theme/, not https://sphinx-themes.org/sample-sites/stanford-theme/. Is that ok?
